SELECT DISTINCT A.OWNER, A.OBJECT_NAME, A.OBJECT_TYPE
  FROM ALL_OBJECTS A
      ,ALL_SOURCE B
WHERE 1=1
--  AND A.OBJECT_TYPE = 'PROCEDURE'
  AND A.OBJECT_NAME = B.NAME
  AND B.TEXT LIKE '%WITH%AS%'
  AND A.OBJECT_TYPE NOT IN ('SYNONYM','TRIGGER')