--SELECT B.COMMENTS, A.* FROM ALL_COL_COMMENTS A, ALL_TAB_COMMENTS B
-- WHERE 1=1
--   AND A.COLUMN_NAME = 'BEFR_ORDR_CD'
--   AND A.TABLE_NAME = B.TABLE_NAME
--UNION
--SELECT B.COMMENTS, A.* FROM ALL_COL_COMMENTS A, ALL_TAB_COMMENTS B
-- WHERE 1=1
--   AND A.COLUMN_NAME = 'PAST_ORDR_CD'
--   AND A.TABLE_NAME = B.TABLE_NAME
--   ;
-- 
 /*
RT처방코드마스터	    SEHRMGR	STORDRCMT	PAST_ORDR_CD
검체검사처방코드마스터	SEHRMGR	SFCORDRCT	PAST_ORDR_CD 1
혈액제제처방코드마스터	SEHRMGR	SLBORDRCT	PAST_ORDR_CD

식사코드	            SEHRMGR	SUDIECDCT	BEFR_ORDR_CD
약품상호작용중복로그	SEHRMGR	MDDURLOGT	BEFR_ORDR_CD
약품코드	            SEHRMGR	SDDDGCDMT	BEFR_ORDR_CD
처방코드기본	        SEHRMGR	MDORDRCMT	BEFR_ORDR_CD
환자검사처방코드기본	SEHRMGR	SWORDRCMT	BEFR_ORDR_CD
 */
   
SELECT * 
  FROM SWORDRCMT 
 WHERE BEFR_ORDR_CD IN ('BT4812','BT4802','BT4872')
 ;