--테이블조회
SELECT COLUMN_ID
     , A.OWNER
     , A.TABLE_NAME
     , B.COLUMN_NAME
     , ','||B.COLUMN_NAME
     , '"'||' '||'"' "AS"
     , B.COMMENTS
     , ',A.'||B.COLUMN_NAME || ' ' || '"'||B.COMMENTS||'"'
     , A.DATA_TYPE||'('||A.DATA_LENGTH||')'
     , DECODE(C.INDEX_NAME,NULL,'','PK')
     , D.COMMENTS
  FROM ALL_TAB_COLS A
      ,ALL_COL_COMMENTS B
      ,(SELECT INDEX_NAME , TABLE_NAME , COLUMN_NAME ,COLUMN_POSITION
          FROM ALL_IND_COLUMNS 
         WHERE INDEX_NAME =  TABLE_NAME || '_PK'
          AND TABLE_NAME = upper(:IN_TABLE_NAME)
        ) C
      ,ALL_TAB_COMMENTS D
 WHERE A.TABLE_NAME = upper(:IN_TABLE_NAME)
   AND A.TABLE_NAME = B.TABLE_NAME
   AND A.TABLE_NAME = C.TABLE_NAME(+)
   AND A.COLUMN_NAME = B.COLUMN_NAME
   AND A.COLUMN_NAME = C.COLUMN_NAME(+)
   AND A.TABLE_NAME = D.TABLE_NAME
   AND A.OWNER = B.OWNER
   AND A.OWNER = D.OWNER
   AND A.OWNER <> 'KUMADM'
 ORDER BY COLUMN_ID
;